In [1]:
%cd ../..

/home/shpotes/Courses/EAFIT/experimental/modelacion-experimental


In [4]:
import numpy as np
from src.identification.non_parametric import correlation

In [10]:
u = np.array([1, 1, -1, 1, -1, 1, 1])
y = np.array([0, 1.2, -1.6, -0.1, -1.12, 1.01, 1.4])

g = correlation.compute_weighting_from_signal(u, y, 5)
g

array([ 0.764, -0.524,  0.204, -0.224,  0.   ])

In [8]:
correlation.simulate_from_seq(g, np.ones_like(g))

array([ 0.764,  0.24 ,  0.444,  0.22 ,  0.22 , -0.544, -0.02 , -0.224,
        0.   ])

In [12]:
sen = np.sin(np.arange(7))
correlation.simulate_from_seq(g, sen)

array([ 0.        ,  0.64288383,  0.25377244, -0.19699608, -0.65513682,
       -0.51094778,  0.10300429,  0.12031693,  0.15779828,  0.06258907,
        0.        ])